### ISSUE TITLE
Logoff-DisconnectedSession: Script Should Not Use Hardcoded Log Path

### ISSUE THREAD

**Issue by aolszowka** [bkuppens/powershell#1]
Instead of hard coding the path to the log directory consider using the following:

`[Environment]::GetFolderPath('ApplicationData')`

I changed mine to `$LogFile = [Environment]::GetFolderPath('ApplicationData') + "\DisconnectedSessions\sessions_" + $([DateTime]::Now.ToString('yyyyMMdd')) + ".log"`

You'll probably also want to ensure that the folder path exists; I created an Ensure-LogFolder method that just gets called prior to the rest of the script execution; nothing fancy:

```
function Ensure-LogFilePath([string]$LogFile)
{
    $LogFileFolder = [System.IO.Path]::GetDirectoryName($LogFile)
    [System.IO.Directory]::CreateDirectory($LogFileFolder)
}
```

You might also want to modify how Write-Log is implemented such that it doesn't rely on the global `$LogFile`, but that is a stylistic choice.

As an aside your commenting system on your blog is broken; otherwise I would have responded there; thank you for the useful script!

**Comment by bkuppens** [comment]
Thank you for the useful remarks. You are absolutely correct about the hardcoded path and the check if the folder exists... I'm going to update it right away. Thank you for notifying me that my commenting is down on my blog. Should be fixed.
