### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by marcnadeau** [bkuppens/powershell#6]
Hi,

I've had some issues with the excluded users filtering...

Ended up reversing the negative logic

`foreach ($session in $DisconnectedSessions)
{
    if ($users.contains($session.Username))
    {
        Write-Log -Message "$($session.Username) excluded"
    }
    else
    {
        logoff $session.ID
        Write-Log -Message $session.Username
    }
}`

**Comment by bkuppens** [comment]
You are correct. The check didn't work. Should be fixed.
The way you implemented it also works but you used the Contains() method instead of the -contains operator. Keep in mind that the Contains() method is case sensitive. The -contains operator is not.
